Server:
  port: 9091

Spring:
  application:
    name: Product Microsevice
  data:
    mongodb:
      host: localhost
      port: 27017
      database: springcart

product:
  currencies:
    - INR
    - USD
    - AUD
    - EUR