Server:
  port: 9091

Spring:
  application:
    name: Product Microsevice
  data:
    mongodb:
      host: localhost
      port: 27017
      database: springcart
  profiles:
    active: dev

product:
  currencies:
    - INR
    - USD
    - AUD
    - EUR

---
#New prod profile

server:
  port: 9094
spring:
  config:
    activate:
      on-profile:
        - prod